using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Linq;
using System.Text;

namespace Jenx.CsSourceCodeGenerators
{
    [Generator]
    public class JenxSimpleFileWelcomeGenerator : ISourceGenerator
    {
        public void Execute(GeneratorExecutionContext context)
        {
            var helloFromAllString = "";

            var txtFiles = context.AdditionalFiles.Where(at => at.Path.EndsWith(".txt"));
            foreach (AdditionalText file in txtFiles)
            {
                string textFileContext = file.GetText(context.CancellationToken).ToString();
                var textLines = textFileContext.Split(new[] { Environment.NewLine }, StringSplitOptions.RemoveEmptyEntries);

                foreach (var name in textLines)
                    helloFromAllString += $@"            Console.WriteLine(""Hi from {name}"");" + Environment.NewLine;
            }

            var myAutoGeneratedCode =
$@"
using System;
namespace Jenx.CompileTimeGenerated
{{
    public static class PersonsWelcome
    {{
        public static void SayHelloFromAll()
        {{
            Console.WriteLine(""Guys, say hello:"");
            Console.WriteLine(""*********************"");
{helloFromAllString}
        }}
    }}
}}";
            context.AddSource("jenxWelcomeFromAll", SourceText.From(myAutoGeneratedCode, Encoding.UTF8));
        }

        public void Initialize(GeneratorInitializationContext context)
        {
        }
    }
}